version: '2'
services:
  gateway:
    build: api-gateway
    command: npm start
    ports:
      - 3001:3001
    restart: on-failure
    networks:
      - some-net
  java-math:
    build: java-math-service
    command: mvn exec:java -Dexec.mainClass="com.salesbox.MathService.App"
    restart: on-failure
    networks:
      - some-net
  java-queue:
    build: java-queue-service
    command: mvn exec:java -Dexec.mainClass="com.salesbox.QueueService.App"
    restart: on-failure
    networks:
      - some-net
  email:
    build: pg-microservice
    command: /bin/bash -c "sleep 10; npm start"
    restart: on-failure
    networks:
      - some-net
  math:
    build: math-microservice
    command: npm start
    networks:
      - some-net
  queue:
    build: queue-microservice
    command: npm start
    networks:
      - some-net

networks:
  some-net:
    driver: bridge
