version: '2'
services:
  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    image: launcher.gcr.io/google/rabbitmq3
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /home/oxygen/Workspace/Code/data/rabbitmq-data:/var/lib/rabbitmq
    networks:
      - some-net
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/oxygen/Workspace/Code/data/postgres:/var/lib/postgresql/data

networks:
  some-net:
    driver: bridge
